/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceSettingsSectionRouteImport } from './routes/_workspace.settings.$section'
import { Route as WorkspaceProjectsProjectIdCurrentRouteImport } from './routes/_workspace.projects.$projectId.current'
import { Route as WorkspaceProjectsProjectIdReviewsReviewIdRouteImport } from './routes/_workspace.projects.$projectId.reviews.$reviewId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsSectionRoute =
  WorkspaceSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceProjectsProjectIdCurrentRoute =
  WorkspaceProjectsProjectIdCurrentRouteImport.update({
    id: '/projects/$projectId/current',
    path: '/projects/$projectId/current',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceProjectsProjectIdReviewsReviewIdRoute =
  WorkspaceProjectsProjectIdReviewsReviewIdRouteImport.update({
    id: '/projects/$projectId/reviews/$reviewId',
    path: '/projects/$projectId/reviews/$reviewId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/projects/$projectId/current': typeof WorkspaceProjectsProjectIdCurrentRoute
  '/projects/$projectId/reviews/$reviewId': typeof WorkspaceProjectsProjectIdReviewsReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceIndexRoute
  '/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/projects/$projectId/current': typeof WorkspaceProjectsProjectIdCurrentRoute
  '/projects/$projectId/reviews/$reviewId': typeof WorkspaceProjectsProjectIdReviewsReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/_workspace/projects/$projectId/current': typeof WorkspaceProjectsProjectIdCurrentRoute
  '/_workspace/projects/$projectId/reviews/$reviewId': typeof WorkspaceProjectsProjectIdReviewsReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/$section'
    | '/projects/$projectId/current'
    | '/projects/$projectId/reviews/$reviewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/$section'
    | '/projects/$projectId/current'
    | '/projects/$projectId/reviews/$reviewId'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/'
    | '/_workspace/settings/$section'
    | '/_workspace/projects/$projectId/current'
    | '/_workspace/projects/$projectId/reviews/$reviewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/$section': {
      id: '/_workspace/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof WorkspaceSettingsSectionRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/projects/$projectId/current': {
      id: '/_workspace/projects/$projectId/current'
      path: '/projects/$projectId/current'
      fullPath: '/projects/$projectId/current'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdCurrentRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/projects/$projectId/reviews/$reviewId': {
      id: '/_workspace/projects/$projectId/reviews/$reviewId'
      path: '/projects/$projectId/reviews/$reviewId'
      fullPath: '/projects/$projectId/reviews/$reviewId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdReviewsReviewIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceSettingsSectionRoute: typeof WorkspaceSettingsSectionRoute
  WorkspaceProjectsProjectIdCurrentRoute: typeof WorkspaceProjectsProjectIdCurrentRoute
  WorkspaceProjectsProjectIdReviewsReviewIdRoute: typeof WorkspaceProjectsProjectIdReviewsReviewIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceSettingsSectionRoute: WorkspaceSettingsSectionRoute,
  WorkspaceProjectsProjectIdCurrentRoute:
    WorkspaceProjectsProjectIdCurrentRoute,
  WorkspaceProjectsProjectIdReviewsReviewIdRoute:
    WorkspaceProjectsProjectIdReviewsReviewIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
